### ISSUE TITLE
How do I revert back?

### ISSUE THREAD

**Issue by sannidhyaroy** [MuntashirAkon/CaptivePortalController#10]
I installed this app on my S22 running OneUI 6 (Android 14). I'm not sure what this app is meant to do but when I installed I assumed this would let me automatically login to a Wi-Fi with a captive portal set up.

I recently joined college and found out that my hostel's Wi-Fi requires every student to login through the captive portal to access the internet and they achieve this through SOPHOS. So, basically whenever my phone connects to this Wi-Fi network, a notification pops up and I require to sign-in to the network. When I tap the notification, it sends me to a webpage where I login using my credentials. And I have to do this step everytime I'm connected to this network.

I expected that it would automatically somehow push my username and password in the background or through some other mechanism would automatically log me into the network automatically whenever I connect to it.

But when I installed and granted the `WRITE_SECURE_SETTINGS` permission and entered my login page address in the app, it stopped giving me the sign-in notification (which is obvious as I wanted it to login automatically) but it didn't log me in. After tinkering around with it and finding no way out, I gave up and uninstalled the app. But even after uninstalling, the phone doesn't send that notification to login to the captive portal anymore. I tried to forget the wifi network and yet that notification from `Android Captive Portal` doesn't show up. In the App Info page of `Android Captive Portal`, I find that the notifications are blocked but the toggle to allow notifications are greyed out.

How do I revert the device state to how it was before?

**Comment by MuntashirAkon** [comment]
The app does exactly what its name says: It allows you to control the captive portal itself, that is, it allows altering the captive portal connectivity checks or disable it altogether as it phones Google bypassing the protection mechanism such as VPN, exposing PIIs such as IP address.

It certainly does not allow anybody to automatically login to a captive server which may use the captive portal to display a login prompt.

To revert back, you need to enable the controller, set mode to “Detect and display prompt” and set captive portal URLs to Google's.

**Comment by sannidhyaroy** [comment]
Oh, I get it now why it's used. I set it to `Detect and Display Prompt` and changed the captive portal URLs to the default GrapheneOS Connectivity Check Servers. Will this work even if I uninstall the app now?

Thank you for your help btw. 💖

**Comment by MuntashirAkon** [comment]
> Oh, I get it now why it's used. I set it to `Detect and Display Prompt` and changed the captive portal URLs to the default GrapheneOS Connectivity Check Servers. Will this work even if I uninstall the app now?

Yes, it should.
