### ISSUE TITLE
toast to fast, how to select presets unknown

### ISSUE THREAD

**Issue by nutpantz** [MuntashirAkon/CaptivePortalController#2]
V100 fdroid
There was a toast when i enabled the controller. But it was too fast to read. 

No idea how to select presets . No menu or settings option

Otherwise everything seems to be working good on pixel 6 proton aosp android 12.  

I'll test other devices and Android versions later.

Thank you for this app.

**Comment by MuntashirAkon** [comment]
> There was a toast when i enabled the controller. But it was too fast to read.

Fixed in 37d51c272c967d26d9975ea482ab3016a49cd540.

> No idea how to select presets . No menu or settings option

Docs updated in v1.1.0 (you can see suggestions when you start typing `http` in any fields)

> I'll test other devices and Android versions later.

If any your test devices run Android 7.1 and earlier, try with v1.1.0 instead of v1.0.0.
