### ISSUE TITLE
screen not displaying correctly

### ISSUE THREAD

**Issue by nutpantz** [MuntashirAkon/CaptivePortalController#3]
V 110 fdroid
Screen not displaying correctly on my Android 9 black view bv9800  device
(Next to detect and display prompt)

![Screenshot_20221018110053](https://user-images.githubusercontent.com/12160507/196510989-50d66860-08d8-4e1e-9c71-b198ae710cf5.png)

**Comment by MuntashirAkon** [comment]
Fixed in cf35bef22826d7f5fa592c00fbd6519be2ee8914
