### ISSUE TITLE
Add Connectivity Check and SUPL replacement?

### ISSUE THREAD

**Issue by secretmango** [MuntashirAkon/CaptivePortalController#8]
Hi, awesome app! Especially that it works without root!

Using the same permissions, would it be possible to replace the Connectivity Check and SUPL servers? GrapheneOS hosts these too, among others.

Would be awesome! I can try to help but unsure.

**Comment by MuntashirAkon** [comment]
The app can already control captive portal and connectivity checks via **mode** and **custom servers** respectively. Replacing SUPL servers require root (you can use supl-replacer Magisk module). There exists no other way.
